### ISSUE TITLE
How to test ?

### ISSUE THREAD

**Issue by monk-blade** [qingxiang-jia/fcitx5-bridge#1]

**Comment by qingxiang-jia** [comment]
Hi, I just updated the readme, does it help?

**Comment by monk-blade** [comment]
Installed following packages on arm64 ubuntu 22.04 desktop
sudo apt install fcitx5 libzmq3-dev fcitx5-modules-dev protobuf-compiler libprotobuf-dev pkg-config

## Error
parallels@ubuntu-linux-22-04-desktop:~/projects/fcitx5-bridge/build$ sudo make -j4 install
[ 66%] Building CXX object CMakeFiles/bridge.dir/msgs.pb.cc.o
[ 66%] Building CXX object CMakeFiles/bridge.dir/bridge.cpp.o
In file included from /home/parallels/projects/fcitx5-bridge/bridge.h:3,
                 from /home/parallels/projects/fcitx5-bridge/bridge.cpp:1:
/home/parallels/projects/fcitx5-bridge/msgs.pb.h:15:2: error: #error "This file was generated by a newer version of protoc which is"
   15 | #error "This file was generated by a newer version of protoc which is"
      |  ^~~~~
In file included from /home/parallels/projects/fcitx5-bridge/msgs.pb.cc:4:

/home/parallels/projects/fcitx5-bridge/msgs.pb.h:15:2: error: #error "This file was generated by a newer version of protoc which is"
   15 | #error "This file was generated by a newer version of protoc which is"
      |  ^~~~~
/home/parallels/projects/fcitx5-bridge/msgs.pb.h:16:2: error: #error "incompatible with your Protocol Buffer headers. Please update"
   16 | #error "incompatible with your Protocol Buffer headers. Please update"
      |  ^~~~~
/home/parallels/projects/fcitx5-bridge/msgs.pb.h:16:2: error: #error "incompatible with your Protocol Buffer headers. Please update"
   16 | #error "incompatible with your Protocol Buffer headers. Please update"
      |  ^~~~~
/home/parallels/projects/fcitx5-bridge/msgs.pb.h:17:2: error: #error "your headers."
   17 | #error "your headers."
      |  ^~~~~
/home/parallels/projects/fcitx5-bridge/msgs.pb.h:17:2: error: #error "your headers."
   17 | #error "your headers."
      |  ^~~~~
In file included from /home/parallels/projects/fcitx5-bridge/msgs.pb.cc:4:
/home/parallels/projects/fcitx5-bridge/msgs.pb.h:29:10: fatal error: google/protobuf/generated_message_tctable_decl.h: No such file or directory
   29 | #include "google/protobuf/generated_message_tctable_decl.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /home/parallels/projects/fcitx5-bridge/bridge.h:3,
                 from /home/parallels/projects/fcitx5-bridge/bridge.cpp:1:
/home/parallels/projects/fcitx5-bridge/msgs.pb.h:29:10: fatal error: google/protobuf/generated_message_tctable_decl.h: No such file or directory
   29 | #include "google/protobuf/generated_message_tctable_decl.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/bridge.dir/build.make:90: CMakeFiles/bridge.dir/msgs.pb.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/bridge.dir/build.make:76: CMakeFiles/bridge.dir/bridge.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/bridge.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by monk-blade** [comment]
Installed following packages on arm64 ubuntu 22.04 desktop
sudo apt install fcitx5 libzmq3-dev fcitx5-modules-dev protobuf-compiler libprotobuf-dev pkg-config

**Comment by qingxiang-jia** [comment]
The error message says the issue: msgs.pb.cc and msgs.pb.h is generated by a newer version of protoc than yours.

You could either get a newer version of protobuf, which might take a lot of efforts. Or you can just regenerate the files (pb.h and pb.cc). For this approach, take a look at the Makefile, you can run "make proto" to generate the files.

**Comment by monk-blade** [comment]
another error appears

parallels@ubuntu-linux-22-04-desktop:~/Music/fcitx5-bridge$ make build
cmake --build ./build
gmake[1]: Entering directory '/home/parallels/Music/fcitx5-bridge/build'
gmake[2]: Entering directory '/home/parallels/Music/fcitx5-bridge/build'
gmake[3]: Entering directory '/home/parallels/Music/fcitx5-bridge/build'
Consolidate compiler generated dependencies of target bridge
gmake[3]: Leaving directory '/home/parallels/Music/fcitx5-bridge/build'
gmake[3]: Entering directory '/home/parallels/Music/fcitx5-bridge/build'
[ 33%] Building CXX object CMakeFiles/bridge.dir/bridge.cpp.o
/home/parallels/Music/fcitx5-bridge/bridge.cpp: In destructor ‘virtual Engine::~Engine()’:
/home/parallels/Music/fcitx5-bridge/bridge.cpp:64:8: error: ‘class zmq::context_t’ has no member named ‘shutdown’
   64 |   ctx->shutdown();
      |        ^~~~~~~~
/home/parallels/Music/fcitx5-bridge/bridge.cpp: In destructor ‘Server::~Server()’:
/home/parallels/Music/fcitx5-bridge/bridge.cpp:143:8: error: ‘class zmq::context_t’ has no member named ‘shutdown’
  143 |   ctx->shutdown();
      |        ^~~~~~~~
gmake[3]: *** [CMakeFiles/bridge.dir/build.make:76: CMakeFiles/bridge.dir/bridge.cpp.o] Error 1
gmake[3]: Leaving directory '/home/parallels/Music/fcitx5-bridge/build'
gmake[2]: *** [CMakeFiles/Makefile2:83: CMakeFiles/bridge.dir/all] Error 2
gmake[2]: Leaving directory '/home/parallels/Music/fcitx5-bridge/build'
gmake[1]: *** [Makefile:136: all] Error 2
gmake[1]: Leaving directory '/home/parallels/Music/fcitx5-bridge/build'
make: *** [Makefile:19: build] Error 2

**Comment by monk-blade** [comment]
Thanks. After compiling cppzmq from source, it is building successfully. How to make it work with https://github.com/qingxiang-jia/full-cloud-pinyin

**Comment by monk-blade** [comment]
Thanks, Its working. Can  you add/guide more languages to https://github.com/qingxiang-jia/full-cloud-pinyin?

**Comment by qingxiang-jia** [comment]
Yes, I will. Thanks.

**Comment by qingxiang-jia** [comment]
Hi @monk-blade , can you write down what you have done to make it work on Ubuntu? I think it would be great to share this in the readme.

**Comment by monk-blade** [comment]
## Install prerequisites in Ubuntu
```bash
 sudo apt install fcitx5 libzmq3-dev fcitx5-modules-dev protobuf-compiler libprotobuf-dev pkg-config autoconf automake libtool curl make g++ unzip git
```

## Compiling cppzmq from the source

Build cppzmq via cmake. This does an out of source build and installs the build files. [download](https://github.com/zeromq/cppzmq) and unzip the lib, cd to directory

    mkdir build
    cd build
    cmake ..
    sudo make -j4 install

## Regenerate proto files, build and install
```bash
make proto
make build
make install
```

**Comment by qingxiang-jia** [comment]
Thank you! I will update the readme.
